#!/usr/bin/bash

echo -n "nhap n = "
read n

sum=0

while [ $n -gt 2 ]; do
  if [ $(($n % 2)) -eq 0 ]; then
    sum=$(expr $sum + $n)
    n=$(expr $n - 2)
  else
    n=$(expr $n -1)
  fi
done

echo $sum
